config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'articles', to: 'articles#index'
  get 'articles/new', to: 'articles#new'
  get 'articles/:id', to: 'articles#show', as: :article
  post 'articles', to: 'articles#create'
  get 'articles/:id/edit', to: 'articles#edit', as: 'edit'
  patch 'articles/:id', to: 'articles#update'
  delete 'articles/:id', to: 'articles#destroy', as: 'destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new # needed to instantiate the form_for
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(article) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
  <%= render "form", article: @article %>
</div>

app/views/articles/index.html.erb
<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">Wikinimous</span>
  <p><%= link_to 'Make new Article', articles_new_path %></p>
</nav>
<div class="container">
<ul>
  <% @articles.each do |article| %>
    <li><%= link_to article.title, article %> <%= link_to edit_path(article) do %>
         <i class="far fa-edit"></i>
        <% end %>
        <%= link_to article_path(article), method: :delete, data: { confirm: "Are you sure you would like to delete?" } do %>
         <i class="far fa-trash-alt"></i>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/articles/new.html.erb
<div class="container">
  <%= render "form", article: @article %>
</div>

app/views/articles/show.html.erb
<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">Wikinimous</span>
  <p><%= link_to 'Back to Main', articles_path %></p>
</nav>
<div class="container">
<h2><%= @article.title %></h2>
  <p class="content"><%= @article.content %></p>
  <p>Article made: <%= @article.created_at %></p>
  <p><%= link_to edit_path(@article) do %>
         <i class="far fa-edit"></i>
        <% end %>
         <%= link_to article_path(@article), method: :delete, data: { confirm: "Are you sure you would like to delete?" } do %>
         <i class="far fa-trash-alt"></i>
        <% end %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>